### PR TITLE
Adds default font via configstore

### PR DESCRIPTION
**Pull request by mgs96**
#3

### CODE REVIEW

**Comment by ammarbinfaisal** [comment]
Hi @mgs96

Sorry, if what I wrote in the issue wasnt very clear but this is not what I meant.

You should add a flag -d --default-font which makes the font passed by the user after this flag as default(it will be used by the digits by default).

It would be good if you somehow check that the font passed by the user is correct(is used by figlet) but I cant think of a way possible other than keeping the allowed fonts in a json file and checking from there. You decide whether that would be okay.

Also, if you want you can add **another PR** to do the same for color(after merge this one so that there aren't any branch conflicts) to add one more to your PR count👍.

Btw thanks for helping.

**Comment by mgs96** [comment]
Ok man, don't worry, I will!

**Comment by ammarbinfaisal** [comment]
Thank you
Make the short flag for --default-font be -F and the one for
--dafault-color be -C.
Unless u have a better idea.
Thanks again

**Comment by ammarbinfaisal** [comment]
Sorry, this was by mistake.
I've never handled PRs before this hacktoberfest :laughing:

**Comment by ammarbinfaisal** [comment]
You haven't made any updates so I am closing this

**Pull request closed without merging**
